# USO:
# sudo docker compose -f docker-compose-server.yml  up --build -d
# sudo docker compose -f docker-compose-server.yml  down
# Listar containeres
# docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

networks:
    local-network-ia:
        name: local-network-ia
        external: true
        driver: bridge

    auth-network:
        external: true

services:
    assjur-api:
        build: .
        image: assjur-api
        container_name: assjur-api
        restart: always

        networks:
            - local-network-ia
            - auth-network

        ports:
            - "127.0.0.1:4001:4001"

        environment:
            - NODE_ENV=production
            - TZ=America/Fortaleza

        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./logs:/app/logs # Mapeia a pasta local ./logs para persistir os logs do container
